### Create User
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "raag41qefrq4t3q4rg@gmail.com",
    "password": "pswrd123"
}

### Update User
PATCH http://localhost:3000/auth/3
Content-Type: application/json

{
    "email": "khaled@outlook.com",
    "password": "yf8/$?/9na?&wsf!/$7()*wq9cntqsqw",
    "firstName": "Khaled",
    "lastName": "Abou Hechmeh"
}

### Get All Users
GET http://localhost:3000/auth

### Get User By Id
GET http://localhost:3000/auth/1

### Delete User By Id
DELETE http://localhost:3000/auth/2