POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "sara@hotmail.com",
    "password": "mdp",
    "name": "sara"
}

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "emile@gmail.com",
    "password": "1234",
    "name": "emile"
}

###
GET http://localhost:3000/auth

###
GET http://localhost:3000/auth/1